schema_version = "1.0.0"
id = "SaveSelection"
version = "1.0.2"
name = "Save Selection"
tagline = "Save selected objects in Blender Format"
maintainer = "Blender Bob"
type = "add-on"
website = "https://github.com/riouxr/SaveSelection"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Robert Rioux"]